# Generated by Django 5.0.4 on 2024-05-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_author_first_name_alter_author_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='', verbose_name='Profile Picture'),
        ),
    ]
